version: '3.5'

services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/api
    depends_on:
      - db-dev

  db-dev:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=drawaday
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
